version: '3.8'

services:
  backend:
    build: ./AnalyticsAPI
    ports:
      - "5000:5000"

  frontend:
    build: ./analytics-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend
